### ISSUE TITLE
Tut Tut tut

### ISSUE THREAD

**Issue by Milk1337** [MihaiVisu/INF2A_Coursework_2#1]
You are bad person

**Comment by MihaiVisu** [comment]
ok

**Comment by Milk1337** [comment]
Can't hide the truth!

**Comment by MihaiVisu** [comment]
ok

**Comment by MihaiVisu** [comment]
ok

**Comment by MihaiVisu** [comment]
Just check the last commits 😬😘😚😉

**Comment by Milk1337** [comment]
What? You can see the state of any repo at anytime so it's all still there! Cheeky.

**Comment by MihaiVisu** [comment]
shh

**Comment by MihaiVisu** [comment]
I don't want to delete commits from the map :(

**Comment by Milk1337** [comment]
Gotta keep that streak, eh?
